context:
  name: "yggdrasil-python-rapidjson"
  version: "1.23.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/yggdrasil_python_rapidjson-${{ version }}.tar.gz
  sha256: cb2363c76de75e030a0563704eb83e9c89b75f20451b7439ba12a73965e9e1e7

build:
  number: 1
  script:
    - if: unix
      then:
        - 'CMAKE_GENERATOR="Ninja" ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --config-settings=cmake.define.RAPIDJSON_INCLUDE_DIRS=rapidjson/include'
    - if: win
      then:
        - 'set "SKBUILD_CMAKE_ARGS=-G Ninja"'
        - '${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --config-settings=cmake.define.RAPIDJSON_INCLUDE_DIRS=rapidjson/include'

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - numpy
        - python
    - cmake >=3.15
    - ninja
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - hatch-fancy-pypi-readme
    - numpy
    - pip
    - python
    - scikit-build-core
    - setuptools_scm
  run:
    - ${{ stdlib('c') }}
    - python
    - numpy

tests:
  - python:
      imports:
        - yggdrasil_rapidjson
  - script:
      - pytest -sv tests
    requirements:
      run:
        - pandas <3.0.0
        - pytest
        - pytz
        - trimesh
        - unyt
    files:
      source:
        - tests/
        - rapidjson/test/example_python.py

about:
  homepage: https://github.com/cropsinsilico/yggdrasil-python-rapidjson
  repository: https://github.com/cropsinsilico/yggdrasil-python-rapidjson
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper around YggdrasilRapidJSON.
  description: |
    A Python wrapper around YggdrasilRapidJSON. YggdrasilRapidJSON is a
    header-only C++ library for JSON operation extended for use with
    yggdrasil
  documentation: https://cropsinsilico.github.io/yggdrasil-python-rapidjson/

extra:
  recipe-maintainers:
    - langmm
